#!/bin/bash

set -ex

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
PACKAGE_DIR="${TOP_DIR}/package"

## build all go binaries
for component in forklift-api forklift-controller openstack-populator ova-provider-server ovirt-populator populator-controller 
do
  echo "compiling component $component"
  go build -C /go/src/github.com/kubev2v/forklift/cmd/$component -buildvcs=false -ldflags="-w -s" -o $PACKAGE_DIR/$component/$component .
done