#!/bin/bash
set -e

mkdir -p bin dist /go/src/github.com/kubev2v/forklift crds dist

if [ -e ./scripts/$1 ]; then
    ./scripts/checkout
    ./scripts/"$@"
else
    ./checkout
    exec "$@"
fi

chown -R $DAPPER_UID:$DAPPER_GID .
